### ISSUE TITLE
issue: index out of range when apply updates with multi keys

### ISSUE THREAD

**Issue by benjamin99** [rueian/pgcapture#27]
in the previous implementations, both the query/value generation processes
https://github.com/rueian/pgcapture/blob/ed805e7a0773599d7e073025062e6467c4fd6453/pkg/sql/builder.go#L48
https://github.com/rueian/pgcapture/blob/ed805e7a0773599d7e073025062e6467c4fd6453/pkg/sink/postgres.go#L516
might reach the index which is out of range when the number of keys is larger than two.

**Comment by rueian** [comment]
Thanks @benjamin99, we have your fix in v0.0.47 now!
