### ISSUE TITLE
What is the reason for dividing block_size by 28?

### ISSUE THREAD

**Issue by unarmedcivilian** [rueian/pgcapture#3]
I was going through the dumper logic, and couldn't understand why block_size is divided by 28? I understand the 24 bytes being subtracted is page header, but couldn't gather from [Postgres docs](https://www.postgresql.org/docs/13/storage-page-layout.html) on what the logic for that might be.

https://github.com/rueian/pgcapture/blob/f79a2714cce43fe0a176834a27e22303d1004ae2/pkg/dblog/dumper.go#L112

**Comment by rueian** [comment]
Hi @unarmedcivilian,

According to the https://www.postgresql.org/docs/13/storage-page-layout.html#PAGE-TABLE:
After subtracting the page header, the remaining space are occupied by the `ItemIdData` and `Items`

Each `ItemId` is 4 bytes and each `Item` has a `HeapTupleHeaderData` which is 23 bytes and actual data which is at least 1 byte.

Therefore the query divides the remaining space by (4+23+1) to get all possible ctids.

**Comment by unarmedcivilian** [comment]
Thank you @rueian
